config/routes.rb
Rails.application.routes.draw do
  # -----------------------------------------------------
  # Home
  # -----------------------------------------------------
  root 'home#index'
  get :about, controller: :home
  get :contact, controller: :home
  get :terms, controller: :home

  # -----------------------------------------------------
  # Templates
  # -----------------------------------------------------
  resources :templates, only: [] do
    collection do
      get :checklist_colorpicker
    end
  end

  # -----------------------------------------------------
  # Users
  # -----------------------------------------------------
  devise_for :users, controllers: {
    passwords:     'users/passwords',
    registrations: 'users/registrations',
    sessions:      'users/sessions',
    confirmations: 'users/confirmations'
  }

  resources :users, controller: 'users/restful', only: [:index, :show] do
    collection do
      get :mypage
      get :profile
    end
  end

  # -----------------------------------------------------
  # Comikets
  # -----------------------------------------------------
  resources :comikets, only: [:index, :show] do
    resources :ckigyos, only: [:index] do
      collection do
        get :ranking
      end
    end
    resources :ckigyo_checklists, only: [:index] do
      collection do
        get :create_map
        get :download
      end
    end
    resources :ccircle_checklists, only: [:index] do
      collection do
        get :create_map
        get :download
      end
    end
  end

  # -----------------------------------------------------
  # Careas
  # -----------------------------------------------------
  resources :careas, only: [:index] do
    resources :cblocks, only: [] do
      resources :clayouts, only: [:index]
    end
  end

  # -----------------------------------------------------
  # Ckigyos
  # -----------------------------------------------------
  resources :ckigyos, only: [:show] do
    collection do
      get :show_modal_template
    end
  end

  # -----------------------------------------------------
  # CkigyoChecklists
  # -----------------------------------------------------
  resources :ckigyo_checklists, only: [:create, :update, :destroy]

  # -----------------------------------------------------
  # CcircleChecklists
  # -----------------------------------------------------
  resources :ccircle_checklists, only: [:create, :update, :destroy]

  # -----------------------------------------------------
  # Comic1s
  # -----------------------------------------------------
  resources :comic1s, only: [:index, :show] do
    resources :c1circles, only: [:index] do
      collection do
        get :search
      end
    end
    resources :c1circle_checklists, only: [:index] do
      collection do
        get :create_map
        get :download
      end
    end
  end

  # -----------------------------------------------------
  # C1blocks
  # -----------------------------------------------------
  resources :c1blocks, only: [:index] do
    resources :c1layouts, only: [:index]
  end

  # -----------------------------------------------------
  # C1circleChecklists
  # -----------------------------------------------------
  resources :c1circle_checklists, only: [:create, :update, :destroy]

  # -----------------------------------------------------
  # Notifications
  # -----------------------------------------------------
  resources :notifications, only: [:index, :show]

  # -----------------------------------------------------
  # Admin
  # -----------------------------------------------------
  namespace :admin do
    get :layouts, controller: :home
    resources :notifications, only: [:index, :show, :create, :update, :destroy]
    resources :users, only: [:index]
  end

  # -----------------------------------------------------
  # Api
  # -----------------------------------------------------
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :users, only: [] do
        collection do
          post :sign_in
        end
      end

      resources :comikets, only: [] do
        resources :ckigyos, only: [:index]
        resources :ckigyo_checklists, only: [:index]
        resources :ccircle_checklists, only: [:index]
      end
      resources :careas, only: [:index]
      resources :cblocks, only: [] do
        resources :clayouts, only: [:index]
      end
      resources :ckigyo_checklists, only: [:create, :update, :destroy]
      resources :ccircle_checklists, only: [:create, :update, :destroy]

      resources :comic1s, only: [] do
        resources :c1blocks, only: [:index]
        resources :c1circle_checklists, only: [:index]
      end
      resources :c1blocks, only: [] do
        resources :c1layouts, only: [:index]
      end
      resources :c1circle_checklists, only: [:create, :update, :destroy]

      resources :notifications, only: [:index, :show]
    end
  end
end

app/views/share/_page_title.html.erb
<div class="page-header header-main">
  <h1><%= content_for?(:title) ? yield(:title) : 'ComiGuide' %></h1>
</div>

app/views/share/_side_nav.html.erb
<div class="nav nav-pills nav-stacked nav-sidebar hidden-xs hidden-sm">
  <% if user_signed_in? %>
    <li><%= link_to t('views.users.mypage'), mypage_users_path %></li>
    <li><%= link_to t('views.users.edit'), edit_user_registration_path %></li>
    <li><%= link_to '企業ブースチェックリスト', comiket_ckigyo_checklists_path(comiket_id: Comiket::MAIN_ID) %></li>
    <li><%= link_to 'サークルチェックリスト', comiket_ccircle_checklists_path(comiket_id: Comiket::MAIN_ID) %></li>
    <li><%= link_to 'COMIC1チェックリスト', comic1_c1circle_checklists_path(comic1_id: Comic1::MAIN_ID) %></li>
  <% else %>
    <li>
      <%= link_to new_user_registration_path do %>
       <i class="fa fa-chevron-circle-up"></i> <%= t('views.users.sign_up') %>
      <% end %>
    </li>
    <li>
      <%= link_to new_user_session_path do %>
       <i class="fa fa-sign-in"></i> <%= t('views.users.sign_in') %>
      <% end %>
    </li>
    <li><%= link_to '企業ブース一覧', comiket_ckigyos_path(comiket_id: Comiket::MAIN_ID) %></li>
    <li><%= link_to 'COMIC1サークル一覧', comic1_c1circles_path(comic1_id: Comic1::MAIN_ID) %></li>
  <% end %>
</div>

app/views/share/_validation_errors.html.erb
<% if resource.errors.present? %>
  <div class="alert alert-danger">
    <ul>
      <% resource.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>