config/routes.rb
Rails.application.routes.draw do
  # -----------------------------------------------------
  # Home
  # -----------------------------------------------------
  root 'home#index'
  get :about, controller: :home
  get :contact, controller: :home
  get :terms, controller: :home

  # -----------------------------------------------------
  # Templates
  # -----------------------------------------------------
  resources :templates, only: [] do
    collection do
      get :checklist_colorpicker
    end
  end

  # -----------------------------------------------------
  # Users
  # -----------------------------------------------------
  devise_for :users, controllers: {
    passwords:     'users/passwords',
    registrations: 'users/registrations',
    sessions:      'users/sessions',
    confirmations: 'users/confirmations'
  }

  resources :users, controller: 'users/restful', only: [:index, :show] do
    collection do
      get :mypage
      get :profile
    end
  end

  # -----------------------------------------------------
  # Comikets
  # -----------------------------------------------------
  resources :comikets, only: [:index, :show] do
    resources :ckigyos, only: [:index] do
      collection do
        get :ranking
      end
    end
    resources :ckigyo_checklists, only: [:index] do
      collection do
        get :create_map
        get :download
      end
    end
    resources :ccircle_checklists, only: [:index] do
      collection do
        get :create_map
        get :download
      end
    end
  end

  # -----------------------------------------------------
  # Careas
  # -----------------------------------------------------
  resources :careas, only: [:index] do
    resources :cblocks, only: [] do
      resources :clayouts, only: [:index]
    end
  end

  # -----------------------------------------------------
  # Ckigyos
  # -----------------------------------------------------
  resources :ckigyos, only: [:show] do
    collection do
      get :show_modal_template
    end
  end

  # -----------------------------------------------------
  # CkigyoChecklists
  # -----------------------------------------------------
  resources :ckigyo_checklists, only: [:create, :update, :destroy]

  # -----------------------------------------------------
  # CcircleChecklists
  # -----------------------------------------------------
  resources :ccircle_checklists, only: [:create, :update, :destroy]

  # -----------------------------------------------------
  # Comic1s
  # -----------------------------------------------------
  resources :comic1s, only: [:index, :show] do
    resources :c1circles, only: [:index] do
      collection do
        get :search
      end
    end
    resources :c1circle_checklists, only: [:index] do
      collection do
        get :create_map
        get :download
      end
    end
  end

  # -----------------------------------------------------
  # C1blocks
  # -----------------------------------------------------
  resources :c1blocks, only: [:index] do
    resources :c1layouts, only: [:index]
  end

  # -----------------------------------------------------
  # C1circleChecklists
  # -----------------------------------------------------
  resources :c1circle_checklists, only: [:create, :update, :destroy]

  # -----------------------------------------------------
  # Notifications
  # -----------------------------------------------------
  resources :notifications, only: [:index, :show]

  # -----------------------------------------------------
  # Admin
  # -----------------------------------------------------
  namespace :admin do
    get :layouts, controller: :home
    resources :notifications, only: [:index, :show, :create, :update, :destroy]
    resources :users, only: [:index]
  end

  # -----------------------------------------------------
  # Api
  # -----------------------------------------------------
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :users, only: [] do
        collection do
          post :sign_in
        end
      end

      resources :comikets, only: [] do
        resources :ckigyos, only: [:index]
        resources :ckigyo_checklists, only: [:index]
        resources :ccircle_checklists, only: [:index]
      end
      resources :careas, only: [:index]
      resources :cblocks, only: [] do
        resources :clayouts, only: [:index]
      end
      resources :ckigyo_checklists, only: [:create, :update, :destroy]
      resources :ccircle_checklists, only: [:create, :update, :destroy]

      resources :comic1s, only: [] do
        resources :c1blocks, only: [:index]
        resources :c1circle_checklists, only: [:index]
      end
      resources :c1blocks, only: [] do
        resources :c1layouts, only: [:index]
      end
      resources :c1circle_checklists, only: [:create, :update, :destroy]

      resources :notifications, only: [:index, :show]
    end
  end
end

app/models/ckigyo_checklist.rb
# == Schema Information
#
# Table name: ckigyo_checklists
#
#  id         :integer          not null, primary key
#  user_id    :integer          not null
#  ckigyo_id  :integer          not null
#  comment    :string(255)
#  cost       :string(255)
#  color      :string(255)      default("black"), not null
#  rank       :integer          default(1), not null
#  created_at :datetime
#  updated_at :datetime
#

require 'csv'

class CkigyoChecklist < ActiveRecord::Base
  include Colors

  # ----------------------------------------------------------
  # Relation
  # ----------------------------------------------------------
  belongs_to :user
  belongs_to :ckigyo

  # ----------------------------------------------------------
  # Validation
  # ----------------------------------------------------------
  validates :user_id,    presence: true, numericality: true
  validates :ckigyo_id,  presence: true, numericality: true
  validates :color,      presence: true
  validates :rank,       presence: true, numericality: true
  validate :ckigyo_exists?

  def self.csv_for_download(ckigyo_checklists)
    csv_data = CSV.generate do |csv|
      ckigyo_checklists.each do |checklist|
        csv << [
          checklist.ckigyo.kigyo_no,
          checklist.ckigyo.name,
          checklist.comment,
          checklist.cost,
          checklist.color
        ]
      end
    end
    csv_data.encode(Encoding::SJIS)
  end

  private

  def ckigyo_exists?
    ckigyo_id.present? && Ckigyo.find(ckigyo_id).present?
  end
end

app/controllers/api/v1/ckigyo_checklists_controller.rb
class Api::V1::CkigyoChecklistsController < Api::V1::BaseController
  load_and_authorize_resource only: [:update, :destroy]

  def index
    @comiket = Comiket.find(params[:comiket_id])
    @ckigyo_checklists = @comiket
                         .ckigyo_checklists
                         .includes(:ckigyo)
                         .where(user_id: current_user.id)
  end

  def create
    @ckigyo_checklist = CkigyoChecklist.new(ckigyo_checklist_create_params)
    @ckigyo_checklist.user = current_user
    @ckigyo_checklist.save!
  end

  def update
    @ckigyo_checklist.update!(ckigyo_checklist_update_params)
  end

  def destroy
    @ckigyo_checklist.destroy!
  end

  private

  def ckigyo_checklist_create_params
    params.require(:ckigyo_checklist).permit(:ckigyo_id, :comment, :cost, :color)
  end

  def ckigyo_checklist_update_params
    params.require(:ckigyo_checklist).permit(:ckigyo_id, :comment, :cost, :color)
  end
end

app/controllers/ckigyo_checklists_controller.rb
class CkigyoChecklistsController < ApplicationController
  authorize_resource

  def index
    @comiket = Comiket.find(params[:comiket_id])
    if request.format.symbol == :json
      @ckigyos = @comiket.ckigyos
      @ckigyo_checklists = @comiket
        .ckigyo_checklists
        .includes(ckigyo: :comiket)
        .where(user: current_user)
    end

    respond_to do |format|
      format.html
      format.json
    end
  end

  def create
    @ckigyo_checklist = CkigyoChecklist.new(create_params)
    @ckigyo_checklist.user = current_user
    respond_to do |format|
      if @ckigyo_checklist.save
        format.json
      else
        format.json { render json: @ckigyo_checklist.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @ckigyo_checklist = CkigyoChecklist.includes(:ckigyo).find(params[:id])
    respond_to do |format|
      if @ckigyo_checklist.update(update_params)
        format.json
      else
        format.json { render json: @ckigyo_checklist.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @ckigyo_checklist = CkigyoChecklist.includes(:ckigyo).find(params[:id])
    respond_to do |format|
      if @ckigyo_checklist.destroy
        format.json
      else
        format.json { render json: @ckigyo_checklist.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_map
    @comiket = Comiket.find(params[:comiket_id])
    respond_to do |format|
      format.pdf do
        pdf = CkigyoChecklistMapPdf.new(comiket_id: @comiket.id, user_id: current_user.id, draw_line: params[:line])
        send_data pdf.render, filename: checklist_filename('pdf'), disposition: 'inline'
      end
    end
  end

  def download
    @comiket = Comiket.find(params[:comiket_id])
    @ckigyo_checklists = @comiket.ckigyo_checklists.includes(:ckigyo).where(user: current_user)
    respond_to do |format|
      format.csv do
        send_data CkigyoChecklist.csv_for_download(@ckigyo_checklists), filename: checklist_filename('csv')
      end
    end
  end

  private

  def create_params
    params.require(:ckigyo_checklist).permit(:ckigyo_id, :comment, :cost, :color)
  end

  def update_params
    params.require(:ckigyo_checklist).permit(:comment, :cost, :color)
  end

  def checklist_filename(extention)
    "ckigyo_checklist_#{Time.now.to_i}.#{extention}"
  end
end

app/views/ckigyo_checklists/_checklists.html.erb
<div id="ckigyo_checklists_controller"
     ng-controller="CkigyoChecklistsCtrl"
     data-comiket-id="<%= comiket.id %>">
  <!-- .btn-group -->
  <div class="btn-group btn-group-justified checklists-functions">
    <div class="btn-group">
      <button type="button" class="btn btn-default" ng-click="reloadCheckLists()">
        <i class="fa fa-refresh"></i>
      </button>
    </div>
    <div class="btn-group">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
        <i class="fa fa-sort"></i>
      </button>
      <ul class="dropdown-menu" role="menu">
        <li><a href="javascript:void(0);" ng-click="setListOrder('ckigyo.id')">企業ブース</a></li>
        <li><a href="javascript:void(0);" ng-click="setListOrder('comment')">コメント</a></li>
        <li><a href="javascript:void(0);" ng-click="setListOrder('cost')">費用</a></li>
        <li><a href="javascript:void(0);" ng-click="setListOrder('color')">カラー</a></li>
      </ul>
    </div>
    <div class="btn-group">
      <button type="button" class="btn btn-default" ng-click="toggleCreateFormActive()">
        <i class="fa fa-plus"></i>
      </button>
    </div>
    <div class="btn-group" dropdown>
      <button type="button" class="btn btn-default dropdown-toggle">
        <i class="fa fa-file-pdf-o"></i>
      </button>
      <ul class="dropdown-menu pull-right" role="menu">
        <li><%= link_to 'PDFマップ（ラインあり）', create_map_comiket_ckigyo_checklists_path(format: :pdf, line: true), target: :_blank %></li>
        <li><%= link_to 'PDFマップ（ラインなし）', create_map_comiket_ckigyo_checklists_path(format: :pdf, line: false), target: :_blank %></li>
      </ul>
    </div>
  <div class="btn-group" dropdown>
    <button type="button" class="btn btn-default dropdown-toggle">
      <i class="fa fa-cloud-download"></i>
    </button>
    <ul class="dropdown-menu pull-right" role="menu">
      <li><%= link_to 'CSV', download_comiket_ckigyo_checklists_path(format: :csv), target: :_blank %></li>
    </ul>
  </div>
  </div>
  <!-- //.btn-group -->

  <%= render 'ckigyo_checklists/form_create' %>

  <!-- .ckigyo-checklists -->
  <ul class="media-list ckigyo-checklists">
    <li class="media checklist"
        ng-repeat="checklist in ckigyo_checklists | orderBy:list_order"
        data-id="{{ checklist.id }}">
      <!-- .media-body -->
      <div class="media-body" style="border-left-color: {{ checklist.color }};">
        <h4 class="media-heading ckigyo-full-info"
            ckigyo-id="{{ checklist.ckigyo.id }}" ckigyo-modal>
          {{ checklist.ckigyo.full_info }}
        </h4>
        <div class="comment">
          <i class="fa fa-comment-o"></i> {{ checklist.comment }}
        </div>
        <div class="cost">
          <i class="fa fa-jpy"></i> {{ checklist.cost }}
        </div>
        <div class="functions">
          <span class="btn-group pull-right">
            <div class="btn btn-default btn-xs" ng-click="checklist.form.update = !checklist.form.update">
              <i class="fa fa-pencil"></i> edit
            </div>
            <div class="btn btn-default btn-xs" ng-click="checklist.form.destroy = !checklist.form.destroy">
              <i class="fa fa-trash-o"></i> delete
            </div>
          </span>
        </div>
      </div>
      <!-- //.media-body -->
      <form class="form-update-ckigyo-checklist"
            ng-show="checklist.form.update"
            onSubmit="return false;">
        <div class="form-group">
          <label><%= CkigyoChecklist.human_attribute_name(:comment) %></label>
          <input class="form-control"
                 name="comment"
                 type="text"
                 ng-model="checklist.comment">
        </div>
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <label><%= CkigyoChecklist.human_attribute_name(:cost) %></label>
              <input class="form-control"
                     name="cost"
                     type="text"
                     ng-model="checklist.cost">
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <label><%= CkigyoChecklist.human_attribute_name(:color) %></label>
              <checklist-colorpicker ng-model="checklist.color"></checklist-colorpicker>
            </div>
          </div>
        </div>
        <div class="btn btn-update btn-block" ng-click="updateCheckList(checklist)">Update</div>
      </form><!-- //form -->
      <form class="form-destroy-ckigyo-checklist" ng-show="checklist.form.destroy">
        <div class="btn btn-delete btn-block" ng-click="destroyCheckList(checklist)">Destroy</div>
      </form><!-- //form -->
    </li>
  </ul>
  <!-- //.ckigyo-checklists -->
</div>

app/views/ckigyo_checklists/_form_create.html.erb
  <div class="panel panel-default" ng-show="create_form_active">
    <div class="panel-heading">
      <h3 class="panel-title">チェックリスト作成</h3>
    </div>
    <div class="panel-body">
      <!-- form.form-create-ckigyo-checklist -->
      <form class="form-create-ckigyo-checklist"
            name="form_create"
            onSubmit="return false;">
        <div class="form-group">
          <label><%= Ckigyo.model_name.human %></label>
          <select name="ckigyo_id"
                  data-ng-options="c.id as c.full_info for c in ckigyos"
                  class="form-control"
                  data-ng-model="new_ckigyo_checklist.ckigyo_id">
          </select>
        </div>
        <div class="form-group">
          <label><%= CkigyoChecklist.human_attribute_name(:comment) %></label>
          <input class="form-control"
                 name="comment"
                 type="text"
                 data-ng-model="new_ckigyo_checklist.comment">
        </div>
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <label><%= CkigyoChecklist.human_attribute_name(:cost) %></label>
              <input class="form-control"
                     name="cost"
                     type="text"
                     data-ng-model="new_ckigyo_checklist.cost"
                     integer>
            </div>
          </div>
          <div class="col-md-6">
            <div class="form-group">
              <label><%= CkigyoChecklist.human_attribute_name(:color) %></label>
              <checklist-colorpicker ng-model="new_ckigyo_checklist.color"></checklist-colorpicker>
            </div>
          </div>
        </div>
        <div class="btn btn-submit btn-block" ng-click="createCheckList(new_ckigyo_checklist)">Create</div>
      </form>
      <!-- //form.form-create-ckigyo-checklist -->
    </div>
  </div>

app/views/ckigyo_checklists/index.html.erb
<% set_page_sub_title t('views.ckigyo_checklists.index.title', comiket_id: @comiket.id) %>

<%= render 'share/page_title' %>

<div class="row">
  <div class="col-md-2">
    <%= render 'share/side_nav' %>
  </div>
  <!-- //.col -->

  <div class="col-md-7" id="ckigyos_controller" ng-controller="CkigyosCtrl" comiket-id="<%= @comiket.id %>">
  　<div class="panel panel-default hidden-xs hidden-sm">
      <div class="panel-body">
        <div class="ckigyo-map-wrapper">
          <a href="javascript:void(0);"
             style="{{ ckigyo.map_style }}"
             ckigyo-id="{{ ckigyo.id }}"
             ng-repeat="ckigyo in ckigyos" ckigyo-modal>{{ ckigyo.kigyo_no }}</a>
        </div>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="pull-right btn btn-xs btn-default" ng-click="toggleListActive()">
          <i class="fa" ng-class="{ 'fa-toggle-on': list_active, 'fa-toggle-off': !list_active }"></i>
        </div>
        <h3 class="panel-title">企業ブース一覧</h3>
      </div>
      <ul class="list-group" ng-show="list_active">
        <li class="list-group-item" ng-repeat="ckigyo in ckigyos | orderBy:list_order">
          <a href="javascript:void(0);" ckigyo-id="{{ ckigyo.id }}" ckigyo-modal>
            {{ ckigyo.full_info }}
          </a>
          <span class="pull-right">
            <button class="btn btn-default btn-xs">
              <i class="fa fa-plus" ng-click="createCheckList(ckigyo)"></i>
            </button>
          </span>
        </li>
      </ul>
    </div>
  </div>
  <!-- //.col -->

  <div class="col-md-3">
    <%= render 'ckigyo_checklists/checklists', comiket: @comiket  %>
  </div>
  <!-- //.col -->
</div>