config/routes.rb
Rails.application.routes.draw do
  # -----------------------------------------------------
  # Home
  # -----------------------------------------------------
  root 'home#index'
  get :about, controller: :home
  get :contact, controller: :home
  get :terms, controller: :home

  # -----------------------------------------------------
  # Templates
  # -----------------------------------------------------
  resources :templates, only: [] do
    collection do
      get :checklist_colorpicker
    end
  end

  # -----------------------------------------------------
  # Users
  # -----------------------------------------------------
  devise_for :users, controllers: {
    passwords:     'users/passwords',
    registrations: 'users/registrations',
    sessions:      'users/sessions',
    confirmations: 'users/confirmations'
  }

  resources :users, controller: 'users/restful', only: [:index, :show] do
    collection do
      get :mypage
      get :profile
    end
  end

  # -----------------------------------------------------
  # Comikets
  # -----------------------------------------------------
  resources :comikets, only: [:index, :show] do
    resources :ckigyos, only: [:index] do
      collection do
        get :ranking
      end
    end
    resources :ckigyo_checklists, only: [:index] do
      collection do
        get :create_map
        get :download
      end
    end
    resources :ccircle_checklists, only: [:index] do
      collection do
        get :create_map
        get :download
      end
    end
  end

  # -----------------------------------------------------
  # Careas
  # -----------------------------------------------------
  resources :careas, only: [:index] do
    resources :cblocks, only: [] do
      resources :clayouts, only: [:index]
    end
  end

  # -----------------------------------------------------
  # Ckigyos
  # -----------------------------------------------------
  resources :ckigyos, only: [:show] do
    collection do
      get :show_modal_template
    end
  end

  # -----------------------------------------------------
  # CkigyoChecklists
  # -----------------------------------------------------
  resources :ckigyo_checklists, only: [:create, :update, :destroy]

  # -----------------------------------------------------
  # CcircleChecklists
  # -----------------------------------------------------
  resources :ccircle_checklists, only: [:create, :update, :destroy]

  # -----------------------------------------------------
  # Comic1s
  # -----------------------------------------------------
  resources :comic1s, only: [:index, :show] do
    resources :c1circles, only: [:index] do
      collection do
        get :search
      end
    end
    resources :c1circle_checklists, only: [:index] do
      collection do
        get :create_map
        get :download
      end
    end
  end

  # -----------------------------------------------------
  # C1blocks
  # -----------------------------------------------------
  resources :c1blocks, only: [:index] do
    resources :c1layouts, only: [:index]
  end

  # -----------------------------------------------------
  # C1circleChecklists
  # -----------------------------------------------------
  resources :c1circle_checklists, only: [:create, :update, :destroy]

  # -----------------------------------------------------
  # Notifications
  # -----------------------------------------------------
  resources :notifications, only: [:index, :show]

  # -----------------------------------------------------
  # Admin
  # -----------------------------------------------------
  namespace :admin do
    get :layouts, controller: :home
    resources :notifications, only: [:index, :show, :create, :update, :destroy]
    resources :users, only: [:index]
  end

  # -----------------------------------------------------
  # Api
  # -----------------------------------------------------
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :users, only: [] do
        collection do
          post :sign_in
        end
      end

      resources :comikets, only: [] do
        resources :ckigyos, only: [:index]
        resources :ckigyo_checklists, only: [:index]
        resources :ccircle_checklists, only: [:index]
      end
      resources :careas, only: [:index]
      resources :cblocks, only: [] do
        resources :clayouts, only: [:index]
      end
      resources :ckigyo_checklists, only: [:create, :update, :destroy]
      resources :ccircle_checklists, only: [:create, :update, :destroy]

      resources :comic1s, only: [] do
        resources :c1blocks, only: [:index]
        resources :c1circle_checklists, only: [:index]
      end
      resources :c1blocks, only: [] do
        resources :c1layouts, only: [:index]
      end
      resources :c1circle_checklists, only: [:create, :update, :destroy]

      resources :notifications, only: [:index, :show]
    end
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  username               :string(255)      not null
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  confirmation_token     :string(255)
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#

class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # ----------------------------------------------------------
  # Relation
  # ----------------------------------------------------------
  has_many :ckigyo_checklists
  has_many :ccircle_checklists
  has_many :c1circle_checklists
  has_one :api_token, dependent: :destroy

  # ----------------------------------------------------------
  # Validation
  # ----------------------------------------------------------
  validates :username, presence: true, format: { with: /\A[a-zA-Z0-9\-_]+\Z/i }, length: { minimum: 4 }

  # ----------------------------------------------------------
  # Scope
  # ----------------------------------------------------------
  scope :confirmed, -> { where.not(confirmed_at: nil) }

  # ----------------------------------------------------------
  # Callback
  # ----------------------------------------------------------
  after_create :add_role_normal

  def remember_me
    true
  end

  def undefined_passsword?
    !!/\A.+@undefined\z/i.match(email)
  end

  private

  def add_role_normal
    add_role :normal
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  def index
    @users = User.page(params[:page]).per(15) if request_json?

    respond_to do |format|
      format.html
      format.json
    end
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::BaseController
  skip_before_action :authenticate_user_from_api_token, only: :sign_in

  def sign_in
    @user = User.find_by(email: user_sign_in_params[:email])
    if @user && @user.valid_password?(user_sign_in_params[:password])
      if @user.confirmed_at?
        @api_token = ApiToken.find_or_initialize_by(user_id: @user.id)
        @api_token.set_token
        @api_token.save!
      else
        render json: { error: 'You have to confirm your account before continuing.' }, status: :unprocessable_entity
      end
    else
      render json: { error: 'Invalid email or password.' }, status: :unprocessable_entity
    end
  end

  private

  def user_sign_in_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  skip_authorization_check
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  skip_authorization_check
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def new
    super
  end

  def create
    super
  end

  def edit
    super
  end

  def update
    super
  end

  def destroy
    super
  end

  protected

  def after_update_path_for(resource)
    mypage_users_path
  end
end

app/controllers/users/restful_controller.rb
class Users::RestfulController < ApplicationController
  before_filter :authenticate_user!

  def index
    raise CanCan::AccessDenied.new unless current_user.admin?
    @users = User.all
  end

  def mypage
    if request.format.symbol == :json
      @user = current_user
      @comiket = Comiket.find(Comiket::MAIN_ID)
      @notifications = Notification.publish.web.recent
      @ckigyo_checklists = @comiket.ckigyo_checklists
                                   .includes(ckigyo: :comiket)
                                   .where(user: current_user)
                                   .order(created_at: :desc)
      @ccircle_checklists = @comiket.ccircle_checklists
                                    .includes(clayout: :cblock)
                                    .where(user: current_user)
                                    .order(created_at: :desc)
      @comic1 = Comic1.find(Comic1::MAIN_ID)
      @c1circle_checklists = @comic1.c1circle_checklists
                                     .includes(c1layout: { c1block: :c1layouts })
                                     .where(user: current_user)
                                     .order(created_at: :desc)
    end

    respond_to do |format|
      format.html
      format.json
    end
  end

  def profile
    @user = current_user
    @page_sub_title = 'プロフィール'
  end

  def my_info
    @user = current_user
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  skip_authorization_check

  def new
    super
  end

  def create
    super
  end

  def destroy
    super
  end
end

app/views/users/restful/_message_panels.html.erb
<div id="user-mypage-message-panels">
  <div class="col-md-4">
    <div class="panel panel-blue">
      <div class="panel-heading">
        <div class="row">
            <div class="col-xs-2">
              <i class="fa fa-users fa-3x"></i>
            </div>
            <div class="col-xs-10 text-right">
              <div class="count">C{{ comiket_id }}サークルチェックリスト {{ list_count.ccircle_checklists }} 件</div>
              <div class="message">
                <%= link_to 'サークルチェックリスト一覧', comiket_ccircle_checklists_path(comiket_id: Comiket::MAIN_ID) %>
              </div>
            </div>
        </div>
      </div>
      <!-- //.panel-heading -->
      <ul class="list-group">
        <li class="list-group-item">
          <b>C{{ comiket_id }} 新着チェックリスト</b>
        </li>
        <li class="list-group-item" ng-repeat="checklist in ccircle_checklists | limitTo : 5">
          {{ checklist.circle_name }}
          <span class="badge pull-right">{{ checklist.created_at | date : 'MM/dd HH:mm' }}</span>
        </li>
      </ul>
    </div>
  </div>
  <!-- //.col -->
  <div class="col-md-4">
    <div class="panel panel-green">
      <div class="panel-heading">
        <div class="row">
            <div class="col-xs-2">
              <i class="fa fa-building fa-3x"></i>
            </div>
            <div class="col-xs-10 text-right">
              <div class="count">C{{ comiket_id }} 企業ブースチェックリスト {{ list_count.ckigyo_checklists }} 件</div>
              <div class="message">
                <%= link_to '企業ブースチェックリスト一覧', comiket_ckigyo_checklists_path(comiket_id: Comiket::MAIN_ID) %>
              </div>
            </div>
        </div>
      </div>
      <!-- //.panel-heading -->
      <ul class="list-group">
        <li class="list-group-item">
          <b>C{{ comiket_id }} 企業ブースチェックリスト</b>
        </li>
        <li class="list-group-item" ng-repeat="checklist in ckigyo_checklists | limitTo : 5">
          {{ checklist.ckigyo.name }}
          <span class="badge pull-right">{{ checklist.created_at | date : 'MM/dd HH:mm' }}</span>
        </li>
      </ul>
    </div>
  </div>
  <!-- //.col -->
  <div class="col-md-4">
    <div class="panel panel-orange">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-2">
            <i class="fa fa-users fa-3x"></i>
          </div>
          <div class="col-xs-10 text-right">
            <div class="count">COMIC1☆{{ comic1_id }} サークルチェックリスト {{ list_count.c1circle_checklists }} 件</div>
            <div class="message">
              <%= link_to 'サークルチェックリスト一覧', comic1_c1circle_checklists_path(comic1_id: Comic1::MAIN_ID) %>
            </div>
          </div>
        </div>
      </div>
      <!-- //.panel-heading -->
      <ul class="list-group">
        <li class="list-group-item">
          <b>COMIC1☆{{ comic1_id }} 新着チェックリスト</b>
        </li>
        <li class="list-group-item" ng-repeat="checklist in c1circle_checklists | limitTo : 5">
          {{ checklist.circle_name }}
          <span class="badge pull-right">{{ checklist.created_at | date : 'MM/dd HH:mm' }}</span>
        </li>
      </ul>
    </div>
  </div>
  <!-- //.col -->
</div>

app/views/users/restful/index.html.erb
<ul class="media-list">
	<% @users.each do |user| %>
  <li class="media">
    <a class="pull-left" href="#">
      <img class="media-object" src="http://placehold.jp/64x64.png">
    </a>
    <div class="media-body">
      <h4 class="media-heading"><%= user.username %></h4>
      <p><%= user.email %></p>
    </div>
  </li>
  <% end %>
</ul>

app/views/users/restful/mypage.html.erb
<% set_page_sub_title t('views.users.restful.mypage.title') %>

<div id="users-mypage-ctrl"
     ng-controller="UsersMypageCtrl"
     data-comiket-id="<%= Comiket::MAIN_ID %>"
     data-comic1-id="<%= Comic1::MAIN_ID %>">

  <%= render 'share/page_title' %>

  <div class="row">
    <div class="col-md-2">
      <%= render 'share/side_nav' %>
    </div>

    <div class="col-md-10">
      <div class="row">
        <div class="col-md-4">
          <div class="panel panel-navy">
            <div class="panel-heading">
              <i class="fa fa-user fa-1x"></i> アカウント
            </div>
            <table class="table">
              <tbody>
                <tr>
                  <th>ユーザー名</th>
                  <td>{{ user.username }}</td>
                </tr>
                <tr>
                  <th>メールアドレス</th>
                  <td>{{ user.email }}</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
        <!-- //.col -->
        <div class="col-md-4">
          <div class="panel panel-warning">
            <div class="panel-heading">
              <div class="row">
                <div class="col-xs-2">
                  <i class="fa fa-bell fa-3x"></i>
                </div>
                <div class="col-xs-10 text-right">
                  <div class="count">新着メッセージ {{ notifications.length }} 件</div>
                  <div class="message">
                    <%= link_to 'メッセージ一覧', notifications_path %>
                  </div>
                </div>
              </div>
            </div>
            <!-- //.panel-heading -->
            <ul class="list-group">
              <li class="list-group-item">
                <b>新着メッセージ</b>
              </li>
              <li class="list-group-item" ng-repeat="notification in notifications | limitTo : 5">
                {{ notification.title }}
                <span class="badge pull-right">{{ notification.published_at | date : 'MM/dd HH:mm' }}</span>
              </li>
            </ul>
          </div>
        </div>
        <!-- //.col -->
      </div>
      <!-- //.row -->
      <div class="row">
        <%= render 'users/restful/message_panels' %>
      </div>
      <!-- //.row -->
    </div>
  </div>
</div>

app/views/users/restful/profile.html.erb
<% set_page_sub_title t('views.users.restful.profile.title') %>

<div>
  <%= render 'share/page_title' %>

  <div class="row">
    <div class="col-md-2">
      <%= render 'share/side_nav' %>
    </div>

    <div class="col-md-10">

    </div>
  </div>
</div>